# Generated by Django 2.1.3 on 2018-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                # ('username', models.CharField(max_length=30)),
                # ('password', models.CharField(max_length=30)),
                # ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
