# Generated by Django 2.1.3 on 2018-11-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petName', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=3)),
                ('birthDate', models.DateField()),
                ('age', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=30)),
                ('sickness', models.CharField(max_length=30)),
            ],
        ),
    ]
